
import { Trade, MarketType } from '../types';

export const DEMO_TRADES: Trade[] = [
  {
    id: "001",
    createdAt: new Date().toISOString(),
    tradeDateTime: "2025-10-07T13:00:00",
    status: 'Cerrado',
    accountId: "default-acc",
    market: 'Cripto',
    asset: "ASTER/USDT",
    direction: "short",
    timeframe: "4h",
    setup: "Retest of resistance on 4H",
    marketSentiment: "Euforia extrema",
    assetSentiment: "Euforia",
    notesUser: "First clear weakness on lower timeframes while price was at resistance during extreme hype",
    thesis: "Resistencia semanal confirmada con divergencia bajista en RSI. Volumen decayendo en el rebote.",
    images: [],
    macroTrend: { macro: 'Bajista', micro: 'Bajista', reversalEvidence: 'sí', htfLevelsChecked: 'sí' },
    riskR: 1,
    entry: 2.13,
    stopLoss: 2.32,
    takeProfits: [1.00, 0.85],
    positionSizeUnits: 5263.15,
    rr: 5.95,
    pnl: { dollars: 6157.89, percent: 615.78, rMultiple: 6.15 },
    executionQuality: 'A',
    qualityScore: 9,
    mentalState: "Neutral",
    reason: "Estrategia confirmada",
    motive: "Siguiendo mi plan",
    alertsTriggered: []
  },
  {
    id: "002",
    createdAt: new Date().toISOString(),
    tradeDateTime: "2025-10-26T20:00:00",
    status: 'Cerrado',
    accountId: "default-acc",
    market: 'Cripto',
    asset: "SOL/USDT",
    direction: "short",
    timeframe: "Daily",
    setup: "Monthly support resistance flip using Weekly and Daily",
    marketSentiment: "Euforia",
    assetSentiment: "Euforia extrema",
    notesUser: "Strong weekly resistance and euphoria during recovery from 171 to 200",
    thesis: "Flip de SR mensual. Nivel psicológico de 200 actuando como techo masivo.",
    images: [],
    macroTrend: { macro: 'Bajista', micro: 'Alcista', reversalEvidence: 'sí', htfLevelsChecked: 'sí' },
    riskR: 2,
    entry: 2.03,
    stopLoss: 2.69,
    takeProfits: [1.54, 1.36, 1.255],
    positionSizeUnits: 1515.15,
    rr: 1.17,
    pnl: { dollars: 1174.24, percent: 58.71, rMultiple: 1.17 },
    executionQuality: 'B',
    qualityScore: 7,
    mentalState: "Neutral",
    reason: "Estrategia confirmada",
    motive: "Continuidad del plan",
    alertsTriggered: ["🟡 RR bajo (< 1.5)"]
  },
  {
    id: "003",
    createdAt: new Date().toISOString(),
    tradeDateTime: "2025-10-05T10:00:00",
    status: 'Cerrado',
    accountId: "default-acc",
    market: 'Cripto',
    asset: "HYPE/USDT",
    direction: "short",
    timeframe: "1h",
    setup: "Support resistance flip first test after breakdown",
    marketSentiment: "Euforia extrema",
    assetSentiment: "Euforia extrema",
    notesUser: "Price dropped from ATH around 59 to 40 and rebounded into resistance near 48",
    thesis: "Primer test tras ruptura de soporte estructural. Reacción violenta esperada.",
    images: [],
    macroTrend: { macro: 'Rango', micro: 'Bajista', reversalEvidence: 'sí', htfLevelsChecked: 'no seguro' },
    riskR: 1,
    entry: 48.50,
    stopLoss: 54.64,
    takeProfits: [35.00],
    positionSizeUnits: 16.28,
    rr: 2.19,
    pnl: { dollars: 219.86, percent: 27.83, rMultiple: 2.19 },
    executionQuality: 'B',
    qualityScore: 6,
    mentalState: "Neutral",
    reason: "Estrategia confirmada",
    motive: "Siguiendo mi plan",
    alertsTriggered: ["🟡 Sentimiento extremo contra dirección"]
  },
  {
    id: "004",
    createdAt: new Date().toISOString(),
    tradeDateTime: "2025-10-30T09:00:00",
    status: 'Cerrado',
    accountId: "default-acc",
    market: 'Cripto',
    asset: "HYPE/USDT",
    direction: "short",
    timeframe: "Daily",
    setup: "Retest of resistance with Daily trend already broken",
    marketSentiment: "Euforia extrema",
    assetSentiment: "Euforia",
    notesUser: "Second short taken with trend after Daily structure break",
    thesis: "Continuación de tendencia bajista tras rotura de Market Structure en Daily.",
    images: [],
    macroTrend: { macro: 'Bajista', micro: 'Bajista', reversalEvidence: 'sí', htfLevelsChecked: 'sí' },
    riskR: 1.5,
    entry: 45.20,
    stopLoss: 54.64,
    takeProfits: [22.00],
    positionSizeUnits: 15.88,
    rr: 2.45,
    pnl: { dollars: 346.17, percent: 48.31, rMultiple: 2.45 },
    executionQuality: 'A',
    qualityScore: 8,
    mentalState: "Neutral",
    reason: "Estrategia confirmada",
    motive: "Continuidad del plan",
    alertsTriggered: []
  },
  {
    id: "005",
    createdAt: new Date().toISOString(),
    tradeDateTime: "2025-10-16T15:00:00",
    status: 'Cerrado',
    accountId: "default-acc",
    market: 'Cripto',
    asset: "BNB/USDT",
    direction: "short",
    timeframe: "Daily",
    setup: "Bearish retest support resistance flip on Daily with SFP context",
    marketSentiment: "Euforia extrema",
    assetSentiment: "Euforia extrema",
    notesUser: "Narrative driven euphoria after Trump pardon to CZ BNB best performer since June",
    thesis: "SFP (Swing Failure Pattern) en máximos locales combinado con euforia narrativa por noticias externas.",
    images: [],
    macroTrend: { macro: 'Alcista', micro: 'Bajista', reversalEvidence: 'sí', htfLevelsChecked: 'sí' },
    riskR: 3,
    entry: 1198,
    stopLoss: 1409,
    takeProfits: [633],
    positionSizeUnits: 14.21,
    rr: 2.67,
    pnl: { dollars: 5072.98, percent: 29.79, rMultiple: 8.02 },
    executionQuality: 'A',
    qualityScore: 10,
    mentalState: "Neutral",
    reason: "Estrategia confirmada",
    motive: "Oportunidad excepcional",
    alertsTriggered: []
  },
  {
    id: "006",
    createdAt: new Date().toISOString(),
    tradeDateTime: "2025-11-08T11:00:00",
    status: 'Cerrado',
    accountId: "default-acc",
    market: 'Cripto',
    asset: "ZEC/USDT",
    direction: "short",
    timeframe: "Daily",
    setup: "Counter trend Daily reversal attempt during super hype",
    marketSentiment: "Euforia extrema",
    assetSentiment: "Euforia extrema",
    notesUser: "Closed due to excessive time above entry and lack of follow through",
    thesis: "Intento de captura de techo en tendencia parabólica. Gestión defensiva al no haber desplazamiento.",
    images: [],
    macroTrend: { macro: 'Alcista', micro: 'Alcista', reversalEvidence: 'no', htfLevelsChecked: 'no seguro' },
    riskR: 1,
    entry: 512,
    stopLoss: 835,
    takeProfits: [227],
    positionSizeUnits: 3.09,
    rr: 0.88,
    pnl: { dollars: -386.25, percent: -24.41, rMultiple: -1.21 },
    executionQuality: 'F',
    qualityScore: 2,
    mentalState: "Neutral",
    reason: "Intuición",
    motive: "FOMO",
    alertsTriggered: ["🔴 Contra tendencia Macro y Micro", "🟡 Setup negativo detectado", "🔴 Setup y Motivo negativos (Operativa emocional)", "🟡 RR bajo (< 1.5)"]
  },
  {
    id: "007",
    createdAt: new Date().toISOString(),
    tradeDateTime: "2025-10-15T09:00:00",
    status: 'Cerrado',
    accountId: "default-acc",
    market: 'Índices',
    asset: "S&P500",
    direction: "short",
    timeframe: "1h",
    setup: "Anticipating weakness top call hedge style short",
    marketSentiment: "Neutral",
    assetSentiment: "Neutral",
    notesUser: "High risk hedge trade closed after repeated strength above key level 6740",
    thesis: "Hedge táctico anticipando rotación de capital. Cerrado por invalidación técnica clara.",
    images: [],
    macroTrend: { macro: 'Alcista', micro: 'Alcista', reversalEvidence: 'no', htfLevelsChecked: 'sí' },
    riskR: 0.5,
    entry: 6582,
    stopLoss: 7300,
    takeProfits: [6000],
    positionSizeUnits: 0.69,
    rr: 0.81,
    pnl: { dollars: -120.75, percent: -2.65, rMultiple: -0.24 },
    executionQuality: 'C',
    qualityScore: 4,
    mentalState: "Incertidumbre",
    reason: "Noticias",
    motive: "Otro",
    alertsTriggered: ["🔴 Contra tendencia Macro y Micro", "🟡 RR bajo (< 1.5)"]
  }
];